# Generated by Django 2.2.12 on 2020-04-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitiBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripduration', models.IntegerField()),
                ('starttime', models.DurationField()),
                ('stoptime', models.DurationField()),
                ('start_station_id', models.IntegerField()),
                ('start_station_name', models.TextField()),
                ('start_station_latitude', models.FloatField()),
                ('start_station_longitude', models.FloatField()),
                ('end_station_id', models.IntegerField()),
                ('end_station_name', models.TextField()),
                ('end_station_latitude', models.FloatField()),
                ('end_station_longitude', models.FloatField()),
                ('bikeid', models.IntegerField()),
                ('usertype', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
        ),
    ]
